import os

OPENAI_API_TYPE = "azure"
AZURE_OPENAI_API_VERSION = "2023-05-15"

EMBEDDING_MODEL = os.getenv("OPENAI_EMBEDDING_MODEL")

GS_CREDENTIALS_PATH = "config/gs_credentials.json"

SHEET_ID = os.getenv("SHEET_ID")
WORKSHEET_NAME = os.getenv("WORKSHEET_NAME")

PINECONE_ENVIRONMENT = os.getenv("PINECONE_ENVIRONMENT")
PINECONE_INDEX_NAME = os.getenv("PINECONE_INDEX_NAME")
